language: python
python:
  - 3.9.7


notifications:
  email:
    recipients:
      - huggins@bu.edu
    on_success: never # default: change
    on_failure: always # default: always

install:
  - pip install -r requirements.txt
  - pip install -U importlib_metadata  # see https://travis-ci.community/t/build-error-for-python-3-7-on-two-different-projects/12895
  - pip install .[dev]

script:
  - python -m unittest discover
  - coverage run --include='viabel/[A-Za-z]*.py' -m pytest
  - coverage report -m  # Generate test coverage report.
  - codecov  # Upload the report to codecov.

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libssl-dev
  - wget https://www.python.org/ftp/python/3.9.6/Python-3.9.6.tgz
  - tar xvf Python-3.9.6.tgz
  - cd Python-3.9.6
  - ./configure --with-openssl=/usr/bin/openssl
  - make
  - sudo make altinstall
  - cd ..





